/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LearnirExp {
        "component": string;
        "consumer": string;
    }
    interface QuizComponent {
        "consumer": string;
        "data": object;
        "options": any;
        "request": Function;
        "submit": Function;
        "submitted": boolean;
    }
}
declare global {
    interface HTMLLearnirExpElement extends Components.LearnirExp, HTMLStencilElement {
    }
    var HTMLLearnirExpElement: {
        prototype: HTMLLearnirExpElement;
        new (): HTMLLearnirExpElement;
    };
    interface HTMLQuizComponentElement extends Components.QuizComponent, HTMLStencilElement {
    }
    var HTMLQuizComponentElement: {
        prototype: HTMLQuizComponentElement;
        new (): HTMLQuizComponentElement;
    };
    interface HTMLElementTagNameMap {
        "learnir-exp": HTMLLearnirExpElement;
        "quiz-component": HTMLQuizComponentElement;
    }
}
declare namespace LocalJSX {
    interface LearnirExp {
        "component"?: string;
        "consumer"?: string;
    }
    interface QuizComponent {
        "consumer"?: string;
        "data"?: object;
        "options"?: any;
        "request"?: Function;
        "submit"?: Function;
        "submitted"?: boolean;
    }
    interface IntrinsicElements {
        "learnir-exp": LearnirExp;
        "quiz-component": QuizComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "learnir-exp": LocalJSX.LearnirExp & JSXBase.HTMLAttributes<HTMLLearnirExpElement>;
            "quiz-component": LocalJSX.QuizComponent & JSXBase.HTMLAttributes<HTMLQuizComponentElement>;
        }
    }
}
