name: Build learnir-exp-module
on:
  push:
    branches:
      - main
jobs:
  build-learnir-exp-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: true
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Build learnir-exp, Publish for Deployment 🚀
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          npm install
          npm run build
      - name: Push generated module to its repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "dist/learnir-exp-module"
          destination-github-username: "Learnir"
          destination-repository-name: "learnir-exp-module"
          user-email: henry@learnir.co
          target-branch: main
      - name: Publish to NPM
        run: |
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_LEARNIR_TOKEN }}
